spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/braveiscoming
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect